--- !ditz.rubyforge.org,2008-03-06/project 
name: Ritz
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: Ritz
- !ditz.rubyforge.org,2008-03-06/component 
  name: Command line interface
- !ditz.rubyforge.org,2008-03-06/component 
  name: Web interface
- !ditz.rubyforge.org,2008-03-06/component 
  name: Storage
- !ditz.rubyforge.org,2008-03-06/component 
  name: Documentation
- !ditz.rubyforge.org,2008-03-06/component 
  name: Racket interface
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: v1.0.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-10-11 23:55:11.077378 Z
    - Matias Eyzaguirre <matias@fortlogic.net>
    - created
    - The first complete release.
- !ditz.rubyforge.org,2008-03-06/release 
  name: v2.0.0
  status: :unreleased
  release_time: 
  log_events: 
  - - 2014-10-11 23:55:39.846796 Z
    - Matias Eyzaguirre <matias@fortlogic.net>
    - created
    - The second major release.
css: style.css
labels: []

